config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, :controllers=>{:sessions=>'employees/sessions',:invitations=>'employees/invitations',:registrations=>'employees/registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :homepage,only:[:index]
  resources :divisions

  root 'homepage#home'
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index
    end
    def home
    end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/_hrmanager_page.html.erb
<div class="container">
<div class="container px-4 text-center">
  <div class="row gx-5">
    <div class="col">
     <div class="p-3">  <p>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Division</button>
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample1">
      <div class="card card-body">
      <%=link_to "View Division", divisions_path %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample2">
      <div class="card card-body">
      <%=link_to "Add New Division", new_division_path %>
      </div>
    </div>
  </div>
</div> </div>
    </div>
    <div class="col">
      <div class="p-3"><p>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample3 multiCollapseExample4">Employee</button>
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample3">
      <div class="card card-body">
    <%=link_to "Add New Employee", new_employee_invitation_path %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample4">
      <div class="card card-body">
        Some placeholder content for the second collapse component of this multi-collapse example. This panel is hidden by default but revealed when the user activates the relevant trigger.
      </div>
    </div>
  </div>
</div></div>
    </div>
  </div>
</div>
</div>

app/views/homepage/home.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Employee Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
       
        
      </ul>
     
      <%=link_to "Login",employee_session_path,{class:"btn btn-outline-success"}%>
    </div>
  </div>
</nav>
</div>
<div class="container">
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%=asset_url("img1.jpg") %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%=asset_url("img2.jpg") %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%=asset_url("img3.jpg") %>" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

app/views/homepage/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Employee Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      
      </ul>
      <div class="d-flex">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

    <li class="nav-item dropdown">
 
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%=current_employee.name%>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= %>">Profile</a></li>
            <li><a class="dropdown-item" href="#">Change Password</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Log out</a></li>
          </ul>
        </li>
              <div class="d-flex">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li><img src="<%=asset_url("Paychex_logo.png") %>" height="50px" class="d-block w-100" alt="..."></li>
            </ul>
            </div>
        </ul>
      </div>
     
    </div>
  </div>
</nav>
<%if current_employee.master_employee_role.name=="HR Manager"%>
<%=render 'hrmanager_page'%>
<%end%>