config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, :controllers=>{:sessions=>'employees/sessions',:invitations=>'employees/invitations',:registrations=>'employees/registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :homepage,only:[:index]
  resources :divisions

  root 'homepage#home'
end

app/models/division.rb
class Division < ApplicationRecord
    # association
    has_many :employees

    # validation
    validates :name, presence: true, length: {in: 2..30}, uniqueness: {case_sensitive: false}

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
    def index
        @divisions=Division.all
    end
    
    def show
        get_division
    end

    # create new division
    def new
        @division=Division.new
    end
    # get division to edit using id
    def edit
        get_division
    end

    # create new division
    def create
        @division=Division.new(get_params)
        if @division.save
            flash[:notice]="Saved Successfully"
            redirect_to divisions_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    # delete division
    def destroy
        get_division
        if @division.destroy
            flash[:notice]="Deleted Successully."
            redirect_to divisions_path
        end
    end

    # update division
    def update
        get_division
        if @division.update(get_params)
            flash[:notice]="Updated Successfuly"
            redirect_to divisions_path
        else
            render :edit, status: :unprocessable_entity
        end

    end

    private
    def get_params
        params.require(:division).permit(:name)
    end
    
    def get_division
        @division=Division.find(params[:id])
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<% if @division.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:!</h4>
    <ul>
        <% @division.errors.each do |error| %>
          <li class="mb-0"><%= error.full_message %></li>
        <% end %>
      </ul>
    <hr>
  <p class="mb-0">Please check and give proper inputs.</p>
</div>
    
  <% end %>
<%= form_with(model: @division) do |d| %>


<div class="mb-3 row">
    <%= d.label :name, "Name",{class:"form-label"} %>
    <%= d.text_field :name, {class:"form-control", placeholder:"Enter division name...", required: "true"} %>
</div>

<div class="mb-3 row">
<center>
    <%=d.submit(class:"btn btn-primary mb-3")%>
    </center>
</div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Edit Division</h1>
<div class="container" >
<%= render 'form'%>
</div>

app/views/divisions/index.html.erb
<h1>Divisions</h1>
<div>
<% @divisions.each do |d|%>
<div>
<%=d.name%>
<%=link_to "Edit",edit_division_path(d.id)%>
<%=link_to "Show",division_path(d.id)%>
<%=button_to "Delete",division_path(d.id),method: :delete, data:{turbo_confirm: "Are Your Sure to Delete?"}%>
</div>
<%end%>
</div>

<%=link_to "Add New Division",new_division_path%>

app/views/divisions/new.html.erb
<h1>New Division</h1>
<div class="container" >
<%= render 'form'%>
</div>